Remizov kostya
Socials4geeks/conosole-aggregator-for-social-networks pull request #17
Opened 2017-05-24 02:41 UTC by Praron

Убрал интерфейсы для Фейсбука, сделал типичный интерфейс, мелкие исправления всякие.

2017-05-24 03:25 UTC, KurakovEgor requested changes

2017-05-24 03:25 UTC, Lolithium commented on dev/core/interfaces/interface_basic.h
> +    int PrintMessages( std::vector<std::map<std::string, std::string>> data );
std::map<std::string, std::string> - тип params

2017-05-24 03:25 UTC, Lolithium commented on dev/core/interfaces/interface_typical.h
> +    int PrintWall( std::vector<std::map<std::string, std::string>> data );
`> >` вместо `>>`. Ну и как везде использовать params

2017-05-24 03:44 UTC, KurakovEgor submitted a review, later dismissed

2017-05-24 06:20 UTC, Nikita-Boyarskikh requested changes

2017-05-24 06:20 UTC, Nikita-Boyarskikh commented on dev/core/interfaces/interface_telegram.cpp
> +int InterfaceTelegram::PrintMessages( std::vector<std::map<std::string, std::string>> data ){
`std::map<std::string. std::string> >> params`

2017-05-24 06:20 UTC, Nikita-Boyarskikh commented on dev/core/interfaces/interface_typical.cpp
> +        std::string reason = data[0].at("reason");
Reason needs to validate

2017-05-24 06:20 UTC, Nikita-Boyarskikh commented on dev/core/interfaces/interface_typical.cpp
> +params split_to_kwargs(std::vector<std::string>& args) {
Это не будет работать. А если пользователь введёт `-a arg1   -b arg2 arg3`? Нужно использовать [getopt_long](http://www.opennet.ru/man.shtml?category=3&russian=0&topic=getopt_long).

2017-05-24 06:20 UTC, Nikita-Boyarskikh commented on dev/core/interfaces/interface_vk.cpp
> +    // std::sort(data.begin(), data.end(),
Убрать комментированный код из пулл-реквеста

2017-05-24 06:20 UTC, Nikita-Boyarskikh commented on dev/core/interfaces/interface_vk.cpp
> +    // for (int i = 0 ; i < data.size(); i++) {
Убрать комментированный код из пулл-реквеста

2017-05-24 06:20 UTC, Nikita-Boyarskikh commented on dev/core/interfaces/interface_vk.cpp
> +    // std::string current_word;
Убрать комментированный код из пулл-реквеста

2017-05-24 06:20 UTC, Nikita-Boyarskikh commented on dev/core/interfaces/interface_vk.cpp
> +        // Request request;
Убрать комментированный код из пулл-реквеста

2017-05-27 08:27 UTC, KurakovEgor approved these changes

2017-05-27 08:27 UTC, Lolithium commented on dev/core/interfaces/interface_typical.cpp
> +          << termcolor::reset << " Please, login. Print 'help' for help." << std::endl;
2 PrintWall?

2017-05-27 08:27 UTC, Lolithium commented on dev/core/interfaces/interface_vk.cpp
> +InterfaceVK::InterfaceVK(): name_of_social_network(vk) {};
"vk"

2017-05-27 08:27 UTC, Nikita-Boyarskikh approved these changes

2017-05-27 08:29 UTC, merged